### ISSUE TITLE
SFTP not working

### ISSUE THREAD

**Issue by edisubaru** [teak/Pussh#1]
Hi, the SFTP function isn't working because it doesn't save the url and always say "no url configured for upload" even if the url is actually in the field.
Thanks

**Comment by teak** [comment]
Im am not able to reproduce this issue. Are you filling out every field? They are all required accept for ether a password or a private key.

**Comment by edisubaru** [comment]
Yes, i am filling every field except from the private key.
Every time i close the soft, it wipe the url field and can never upload it like i said.
It's maybe because i use 10.10.3 (14D72i) ...

**Comment by night** [comment]
I cannot reproduce this either (with a fresh install, cleared app data). What URL are you entering in the field? Is it something unusual? Are you pasting the URL or typing it?

**Comment by edisubaru** [comment]
Hi, i had entered this url in the field : https://screen.edisubaru.co/ .
I use it with screencloud and it works well...

**Comment by night** [comment]
> Are you pasting the URL or typing it?

The above question also matters, since there could be an issue registering that you've typed something if it was pasted.

**Comment by edisubaru** [comment]
I tried both

**Comment by edisubaru** [comment]
With the latest build it works well ! 
Thanks :)

**Comment by edisubaru** [comment]
It worked well until I changed server, since then I can't get it to work
Here is the log from the dev console 
`index.js:217 Uploading /Users/edisubaru/Desktop/Capture d’écran 2016-01-30 à 05.53.19.png
index.js:12 Caught exception:  TypeErrormessage: "must start with number, buffer, array or string"stack: (...)get stack: function () { [native code] }arguments: nullcaller: nulllength: 0name: ""prototype: StackTraceGetter__proto__: function Empty() {}<function scope>set stack: function () { [native code] }arguments: nullcaller: nulllength: 1name: ""prototype: StackTraceSetter__proto__: function Empty() {}<function scope>No Scopes__proto__: Errorconstructor: function TypeError() { [native code] }name: "TypeError"stack: (...)get stack: function () { [native code] }set stack: function () { [native code] }__proto__: d
buffer.js:48 Uncaught TypeError: must start with number, buffer, array or string`

**Comment by teak** [comment]
At this point I cant reproduce the issue, and we have made so many code changes it is likely already fixed when we release the new version.

**Comment by edisubaru** [comment]
Hey, I tried with the new electron version and I still get an error :/
first this http://puu.sh/onu0m/c329c0d09b.png and then http://puu.sh/onu2k/e5e80bc638.png

**Comment by teak** [comment]
Ahh. The SFTP upload is broken in dev because of a missing dependency. Likely a different issue then you were having before :/

**Comment by night** [comment]
We published a new release available at https://github.com/teak/Pussh/releases. SFTP works in the release for me. If you continue having issues, it's probably due to the non-ascii characters in your filename, but we should be properly handling them in this latest release.
