### ISSUE TITLE
No url configured for upload.

### ISSUE THREAD

**Issue by jakeoid** [teak/Pussh#12]
Its plaguing me too, can't figure out why. Thinking that something is definitely wrong on the App's end and not my own as i've done my best to troubleshoot. Running OSX Yosemite (10.10.5). Server is near fresh install running a server for one of my own projects + a fresh install of Apache that was put on here just for the purpose. 

_I've blurred out the images for my own privacy_

![screen shot 2016-01-28 at 9 03 04 pm](https://cloud.githubusercontent.com/assets/13518213/12641284/d64a409e-c602-11e5-9ba4-4dae3d2d1ecb.png)
![screen shot 2016-01-28 at 9 03 23 pm](https://cloud.githubusercontent.com/assets/13518213/12641285/d655347c-c602-11e5-8d8e-b8b42cd16e83.png)

**Comment by night** [comment]
This is probably because you are not prefixing the URL with `http(s)://`.. We also published a new version to https://github.com/teak/Pussh/releases if you wish to check it out.
