### ISSUE TITLE
Issue with Windows version of Pussh.

### ISSUE THREAD

**Issue by ghost** [teak/Pussh#18]
Hey,

I'm unsure as to if this project is still being actively maintained or not, however, I feel like I should bring an issue to your attention anyways. Firstly, the mac version of Pussh is absolutely amazing, no issues for me. However, I tried to install it on Windows too, so that I can take screenshots easily.

Here is a gif of me trying to use Pussh on Windows: https://i.imgur.com/RYfM061.gifv.
The issues I receive:
- When I do anything on Pussh for Windows, the app freezes for a few seconds and then carries out the action, this doesn't happen on the mac version.
- When I try to change what happens to my screenshot, it doesn't work, it constantly stays as Imgur, I'm able to take screenshots, it uploads them and gives me the link, but I would like to use HTTP Post instead. On the mac version, I'm able to change what happens to my screenshot, and it works fine.

If you're already aware of these issues, however you're busy with other things, then that's fine, and I'm sorry for bothering you with unneeded notifications. However, at least I can live life without it being on my shoulders that I didn't report issues.

Thanks!

(Note: I installed the other screenshot tool for the purpose of making that gif, to show you the issue. It's not what's causing the issue as this issue occurred prior to downloading the other tool)

**Comment by teak** [comment]
I'm am not aware of this issue, and I don't have any explanation as to its cause. The settings page should open almost instantly, and I cant see any reason for it delay and than continue. If there is some issue with the app I would expect it to crash outright.

I can say I use Pussh on Windows myself and have no issue. The difference in the Mac and Windows versions are mostly in screenshot capture and should not effect settings. My guess is something on your system is interfering with Electron in some way.

As for project activity, I still would like to continue to maintain the project, however I have little time for it at present.
