### ISSUE TITLE
Cannot build project on Windows 8.1x64

### ISSUE THREAD

**Issue by mcrozz** [teak/Pussh#6]
package.sh fails at **sudo npm install -g node-gyp nw-gyp n**
There is no such command as sudo in Windows environment.

And I cannot figure out what actually module is "n"? But anyways, as Node's npm says, this module (n) is not supported by win32

**Comment by teak** [comment]
The build script is for OS X only. Building on Windows is more complex. Im not sure how we will handle packaging on windows.

Honestly I have no idea how to write a build script on Windows. I dont understand how people actually do real work on an OS that refuses to use a real command line interface.

**Comment by mcrozz** [comment]
It's actually not **that** bad :)

I've tried installing node-webkit-builder and run through it. But *keytar* dependency is failing to install. Will search this problem later. I may help with building system for Windows family.

**Comment by Zelakto** [comment]
Hey, this topic may seem a bit old, but did you actually figure it out and get it working? This seems like the only SFTP uploader that is actually good looking, but sadly it's only for OS X. :(

**Comment by teak** [comment]
I have multiple different types of builds "working" under windows. Most recently testing out using Electron instead of NWJS. Still no build script. Windows support is our top priority for the next update.

**Comment by teak** [comment]
Please try again with the latest build. It is now automated.
