### ISSUE TITLE
Breakpad initialization & PHP Post not being recieved

### ISSUE THREAD

**Issue by Aotik** [teak/Pussh#9]
First of all great work with the whole project. Just came across a few issues, first one being an error when the app is run with `nodewebkit` in Terminal. Was wondering if anyone had the same issue and if so how it was fixed; anyway I keep receiving:

`[73768:1105/091345:ERROR:breakpad_mac.mm(238)] Breakpad initializaiton failed`

Works fine if I package it up and run it, but its time consuming when making simple changes. Currently running Yosemite 10.10.3. Tried some things others have suggested online (quite a common thing), but doesn't seem to fix the problem.

Secondly, I've tried using the HTTP POST feature, however I'm not having any luck on logging what is being received within my PHP script, just logs an empty file. Does anyone maybe have a sample script on how they receive the post?

Any help would be greatly appreciated.
Cheers.

**Comment by teak** [comment]
The latest version of the app is built with Electron and has an automated build script. I would guess this issue is no longer valid because of this. Closing..
